name: Silvia Fuentes, Visual Designer
markdown: kramdown
permalink: /blog/:year/:month/:day/:title.html
plugins_dir:
  - jekyll-sitemap
gems:
  - jekyll-sitemap
twitter_username:     silviafuen
github_username:      silviafuen
linkedin_username:    silviafuen
behance_username:     silviafuen
